"""
OSCAL System Security Plan (SSP) document builder.

Produces a conformant OSCAL v1.2.1 system-security-plan JSON structure
from :class:`~ssp_generator.system_model.SystemData` (QVD-derived) and
:class:`~ssp_generator.system_model.SystemConfig` (user-supplied metadata).

Document structure
------------------
metadata
    Standard OSCAL metadata block — title, version, roles, parties.

import-profile
    Reference to the NIST 800-53 Rev 5 baseline profile (configurable).

system-characteristics
    System IDs, name, description, FIPS 199 categorisation, authorization
    boundary.  Information types default to a placeholder that must be
    updated to reference the applicable SP 800-60 Vol II type.

system-implementation
    users           — placeholder roles; must be updated with real user data.
    components      — one "this-system" component + one per unique host IP
                      from the Nessus main QVD + optional software components.
    inventory-items — one per unique host IP; enriched with port/protocol
                      props from the PPSM QVD when available.

control-implementation
    One implemented-requirement per unique NIST 800-53 control found in the
    Control_Temp field.  Satisfaction status is derived from open findings:

        satisfied          — control referenced in findings but no open findings
        partially-satisfied — open Low/Medium findings only
        not-satisfied      — any open High or Very High finding

    Evidence from the Compliance QVD (when provided) is attached as
    remarks on the by-component element.

back-matter
    Resource entry referencing the source QVD files.

References
----------
- OSCAL SSP metaschema: OSCAL/src/metaschema/oscal_ssp_metaschema.xml
- NIST SP 800-18 (SSP guidance)
- NIST SP 800-30 Rev 1 (risk vocabulary)
- OSCAL specification: https://pages.nist.gov/OSCAL
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from typing import Optional

from .system_model import (
    ComplianceResult,
    HostRecord,
    PortEntry,
    SoftwareEntry,
    SystemConfig,
    SystemData,
)

# Import deterministic UUID helpers from the sibling poam_generator package
# so we share the same CLaaS namespace and avoid divergent UUIDs.
from poam_generator.uuid_utils import det_uuid, rand_uuid

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OSCAL_VERSION = "1.2.1"
_NS_OSCAL = "http://csrc.nist.gov/ns/oscal"
_NS_FEDRAMP = "https://fedramp.gov/ns/oscal"

# NIST 800-53 Rev 5 catalog identifier (used as the catalog-uuid reference)
_NIST_800_53_REV5_UUID = "74c8ba1e-5cd4-4ad1-bbfd-d888e2f6c724"

# Severity → OSCAL implementation status derivation
# HIGH/VERY HIGH open finding → not-satisfied (remediation required urgently)
# MEDIUM/LOW open finding → partial (partially implemented)
_HIGH_SEVERITIES = {"very high", "high"}


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _now() -> str:
    """Current UTC time as RFC 3339."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _date_to_rfc3339(iso_date: Optional[str]) -> Optional[str]:
    """Convert YYYY-MM-DD string to RFC 3339 datetime string, or None."""
    if not iso_date:
        return None
    return f"{iso_date}T00:00:00Z"


# ---------------------------------------------------------------------------
# metadata
# ---------------------------------------------------------------------------

def _metadata(config: SystemConfig) -> dict:
    party_uuid = det_uuid(f"party:{config.org_name}")
    roles = [{"id": r["id"], "title": r["title"]} for r in config.roles]
    return {
        "title": f"System Security Plan — {config.system_name}",
        "last-modified": _now(),
        "version": config.version,
        "oscal-version": OSCAL_VERSION,
        "roles": roles,
        "parties": [
            {
                "uuid": party_uuid,
                "type": "organization",
                "name": config.org_name,
            }
        ],
        "responsible-parties": [
            {
                "role-id": "prepared-by",
                "party-uuids": [party_uuid],
            }
        ],
        "remarks": (
            "This SSP was generated by the CLaaS OSCAL SSP Generator from "
            "Nessus QVD scan data.  Sections marked 'REQUIRED' must be "
            "completed by the system owner before ATO submission."
        ),
    }


# ---------------------------------------------------------------------------
# import-profile
# ---------------------------------------------------------------------------

def _import_profile(config: SystemConfig) -> dict:
    return {
        "href": config.baseline_profile_href,
        "remarks": (
            f"NIST SP 800-53 Rev 5 baseline profile. "
            f"Update href if a tailored or agency-specific profile is used."
        ),
    }


# ---------------------------------------------------------------------------
# system-characteristics
# ---------------------------------------------------------------------------

def _information_types(config: SystemConfig) -> list[dict]:
    types = []
    for it in config.information_types:
        obj: dict = {
            "uuid": det_uuid(f"info-type:{config.system_name}:{it.title}"),
            "title": it.title,
            "description": it.description,
            "confidentiality-impact": {
                "base": it.confidentiality_impact,
            },
            "integrity-impact": {
                "base": it.integrity_impact,
            },
            "availability-impact": {
                "base": it.availability_impact,
            },
        }
        if it.sp800_60_id:
            obj["categorizations"] = [
                {
                    "system": "https://doi.org/10.6028/NIST.SP.800-60v2r1",
                    "information-type-ids": [it.sp800_60_id],
                }
            ]
        types.append(obj)
    return types


def _system_characteristics(data: SystemData, config: SystemConfig) -> dict:
    system_uuid = config.system_id or det_uuid(f"system:{config.system_name}")
    short_name = config.system_name_short or config.system_name.split()[0]

    chars: dict = {
        "system-ids": [
            {
                "identifier-type": "https://ietf.org/rfc/rfc4122",
                "id": system_uuid,
            }
        ],
        "system-name": config.system_name,
        "system-name-short": short_name,
        "description": config.system_description,
        "props": [
            {
                "name": "scan-host-count",
                "value": str(len(data.hosts)),
                "ns": _NS_OSCAL,
                "remarks": "Number of unique host IPs found in the Nessus QVD.",
            }
        ],
        "security-sensitivity-level": config.security_sensitivity_level,
        "system-information": {
            "information-types": _information_types(config),
        },
        "security-impact-level": {
            "security-objective-confidentiality": config.confidentiality_impact,
            "security-objective-integrity": config.integrity_impact,
            "security-objective-availability": config.availability_impact,
        },
        "status": {
            "state": config.authorization_status,
        },
        "authorization-boundary": {
            "description": config.boundary_description,
        },
    }

    if config.date_authorized:
        chars["date-authorized"] = config.date_authorized

    return chars


# ---------------------------------------------------------------------------
# system-implementation — components
# ---------------------------------------------------------------------------

def _this_system_component(config: SystemConfig) -> dict:
    """The mandatory 'this-system' component representing the overall system."""
    return {
        "uuid": det_uuid(f"component:this-system:{config.system_name}"),
        "type": "this-system",
        "title": config.system_name,
        "description": config.system_description,
        "status": {"state": "operational"},
        "responsible-roles": [
            {"role-id": "system-owner"},
        ],
    }


def _host_component(host: HostRecord, config: SystemConfig) -> dict:
    """One component per unique host IP address."""
    comp_uuid = det_uuid(f"component:host:{host.ip_address}")
    props = [
        {"name": "asset-id",       "value": host.ip_address,      "ns": _NS_OSCAL},
        {"name": "asset-type",     "value": "computing-device",   "ns": _NS_OSCAL},
        {"name": "scan-type",      "value": "Nessus",             "ns": _NS_OSCAL},
        {"name": "credentialed-scan", "value": host.credentialed_scan, "ns": _NS_OSCAL},
    ]
    if host.host_key_id:
        props.append({"name": "mac-address", "value": host.host_key_id, "ns": _NS_OSCAL})
    if host.os_name:
        props.append({"name": "operating-system", "value": host.os_name, "ns": _NS_OSCAL})
    if host.netbios_name:
        props.append({"name": "netbios-name", "value": host.netbios_name, "ns": _NS_OSCAL})

    return {
        "uuid": comp_uuid,
        "type": "software",         # 'software' covers OS + application hosts
        "title": host.ip_address,
        "description": (
            f"Host {host.ip_address} identified by Nessus vulnerability scan. "
            f"Program Host ID: {host.program_host_id or 'N/A'}."
        ),
        "props": props,
        "status": {"state": "operational"},
    }


def _software_components(
    software: list[SoftwareEntry],
) -> list[dict]:
    """Unique software-type components derived from the Software QVD."""
    seen: set[str] = set()
    comps: list[dict] = []
    for sw in software:
        key = sw.software_key or sw.software
        if key in seen or not key:
            continue
        seen.add(key)
        comps.append(
            {
                "uuid": det_uuid(f"component:software:{key}"),
                "type": "software",
                "title": sw.software,
                "description": f"Software component identified by Nessus scan: {key}",
                "props": [
                    {"name": "software-identifier", "value": key, "ns": _NS_OSCAL},
                ],
                "status": {"state": "operational"},
            }
        )
    return comps


# ---------------------------------------------------------------------------
# system-implementation — users
# ---------------------------------------------------------------------------

def _users(config: SystemConfig) -> list[dict]:
    """
    Placeholder user entries.

    The OSCAL spec requires at least one user.  The generator creates a
    generic 'system-user' placeholder; the system owner must replace this
    with real privileged and non-privileged user role definitions.
    """
    return [
        {
            "uuid": det_uuid(f"user:system-owner:{config.system_name}"),
            "title": "System Owner",
            "role-ids": ["system-owner"],
            "remarks": "REQUIRED — Replace with actual system owner information.",
        },
        {
            "uuid": det_uuid(f"user:admin:{config.system_name}"),
            "title": "System Administrator",
            "props": [
                {"name": "type", "value": "internal", "ns": _NS_OSCAL},
                {"name": "privilege-level", "value": "privileged", "ns": _NS_OSCAL},
            ],
            "remarks": "REQUIRED — Enumerate all privileged user roles per NIST SP 800-18.",
        },
    ]


# ---------------------------------------------------------------------------
# system-implementation — inventory-items
# ---------------------------------------------------------------------------

def _inventory_item(
    host: HostRecord,
    ports_by_ip: dict[str, list[PortEntry]],
    software_by_ip: dict[str, list[SoftwareEntry]],
    config: SystemConfig,
) -> dict:
    """One OSCAL inventory-item per host IP."""
    comp_uuid = det_uuid(f"component:host:{host.ip_address}")
    system_uuid = config.system_id or det_uuid(f"system:{config.system_name}")

    props: list[dict] = [
        {"name": "ipv4-address",   "value": host.ip_address,       "ns": _NS_OSCAL},
        {"name": "asset-id",       "value": host.ip_address,       "ns": _NS_OSCAL},
        {"name": "asset-type",     "value": "computing-device",    "ns": _NS_OSCAL},
        {"name": "scan-type",      "value": "Nessus",              "ns": _NS_OSCAL},
        {"name": "credentialed-scan", "value": host.credentialed_scan, "ns": _NS_OSCAL},
    ]
    if host.host_key_id:
        props.append({"name": "mac-address", "value": host.host_key_id, "ns": _NS_OSCAL})
    if host.os_name:
        props.append({"name": "operating-system", "value": host.os_name, "ns": _NS_OSCAL})
    if host.netbios_name:
        props.append({"name": "netbios-name", "value": host.netbios_name, "ns": _NS_OSCAL})
    if host.scan_date:
        props.append({"name": "scan-date", "value": host.scan_date, "ns": _NS_OSCAL})

    # Port/Protocol/Service props from PPSM
    for pe in ports_by_ip.get(host.ip_address, []):
        props.append({
            "name": "port-protocol-service",
            "value": f"{pe.port}/{pe.protocol}/{pe.svc_name}",
            "ns": _NS_OSCAL,
        })

    # Implemented-components: link to host component and each software component
    impl_comps = [
        {
            "component-uuid": comp_uuid,
            "remarks": f"Host component for {host.ip_address}",
        }
    ]
    for sw in software_by_ip.get(host.ip_address, []):
        sw_uuid = det_uuid(f"component:software:{sw.software_key or sw.software}")
        impl_comps.append(
            {
                "component-uuid": sw_uuid,
                "remarks": f"Software: {sw.software_key or sw.software}",
            }
        )

    return {
        "uuid": det_uuid(f"inventory:{host.ip_address}"),
        "description": (
            f"Host {host.ip_address} identified in Nessus scan. "
            f"Scan date: {host.scan_date or 'unknown'}."
        ),
        "props": props,
        "implemented-components": impl_comps,
    }


# ---------------------------------------------------------------------------
# control-implementation
# ---------------------------------------------------------------------------

_SEVERITY_ORDER = {"very high": 3, "high": 2, "medium": 1, "low": 0, "info": -1}


def _implementation_status(control_id: str, hosts: list[HostRecord]) -> str:
    """
    Derive OSCAL implementation status for a control across all hosts.

    Rules (most severe open finding wins):
      any open High/Very High  →  not-satisfied
      any open Medium/Low      →  partial
      no open findings         →  implemented
    """
    worst: int = -2   # sentinel: no findings at all
    for h in hosts:
        for sev in h.open_controls.get(control_id, []):
            rank = _SEVERITY_ORDER.get(sev.lower(), 0)
            if worst == -2 or rank > worst:
                worst = rank

    if worst == -2:
        return "implemented"    # control referenced but no open findings
    if worst >= _SEVERITY_ORDER["high"]:
        return "not-satisfied"
    return "partial"


def _compliance_remarks(
    control_id: str,
    compliance: list[ComplianceResult],
) -> str:
    """
    Build a remarks string from compliance results whose Reference field
    mentions this control ID.
    """
    control_upper = control_id.upper()
    relevant = [
        c for c in compliance
        if control_upper in c.reference.upper()
    ]
    if not relevant:
        return ""

    lines: list[str] = [f"Compliance evidence for {control_upper}:"]
    for c in relevant[:10]:   # cap at 10 entries to avoid oversized remarks
        lines.append(
            f"  [{c.result}] {c.compliance_test} "
            f"(Host: {c.host_key}, Plugin: {c.plugin_id})"
        )
    if len(relevant) > 10:
        lines.append(f"  ... and {len(relevant) - 10} more results.")
    return "\n".join(lines)


def _open_finding_summary(control_id: str, hosts: list[HostRecord]) -> str:
    """Summary string listing all open findings for a control."""
    lines: list[str] = []
    for h in hosts:
        sevs = h.open_controls.get(control_id)
        if sevs:
            sev_str = ", ".join(sorted(set(sevs), key=lambda s: -_SEVERITY_ORDER.get(s.lower(), 0)))
            lines.append(f"  {h.ip_address}: {sev_str}")
    if not lines:
        return "No open findings."
    return "Open findings:\n" + "\n".join(lines)


def _implemented_requirement(
    control_id: str,
    data: SystemData,
    config: SystemConfig,
) -> dict:
    """Build one OSCAL implemented-requirement for a single control."""
    system_comp_uuid = det_uuid(f"component:this-system:{config.system_name}")
    status = _implementation_status(control_id, data.hosts)

    comp_remarks_parts: list[str] = [
        _open_finding_summary(control_id, data.hosts),
    ]
    compliance_note = _compliance_remarks(control_id, data.compliance)
    if compliance_note:
        comp_remarks_parts.append(compliance_note)

    # Count affected hosts
    affected_hosts = [h for h in data.hosts if control_id in h.open_controls]

    by_component: dict = {
        "component-uuid": system_comp_uuid,
        "description": (
            f"Control {control_id.upper()} implementation status derived from "
            f"CLaaS Nessus scan data.  "
            f"Affected hosts with open findings: {len(affected_hosts)}."
        ),
        "props": [
            {
                "name": "implementation-status",
                "value": status,
                "ns": _NS_FEDRAMP,
            }
        ],
        "remarks": "\n\n".join(filter(None, comp_remarks_parts)),
    }

    req: dict = {
        "uuid": det_uuid(f"impl-req:{control_id}:{config.system_name}"),
        "control-id": control_id,
        "props": [
            {
                "name": "implementation-status",
                "value": status,
                "ns": _NS_FEDRAMP,
            }
        ],
        "set-parameters": [],
        "statements": [
            {
                "statement-id": f"{control_id}_smt",
                "uuid": det_uuid(f"stmt:{control_id}:{config.system_name}"),
                "description": (
                    f"REQUIRED — Provide the control implementation narrative for "
                    f"{control_id.upper()} per NIST SP 800-53 Rev 5.  "
                    f"CLaaS has automatically set the implementation status to "
                    f"'{status}' based on scan findings."
                ),
                "by-components": [by_component],
            }
        ],
        "by-components": [by_component],
    }

    return req


def _control_implementation(data: SystemData, config: SystemConfig) -> dict:
    """Build the full control-implementation section."""
    control_ids = sorted(data.all_control_ids)

    implemented_requirements = [
        _implemented_requirement(cid, data, config)
        for cid in control_ids
    ]

    return {
        "description": (
            "Control implementations derived from CLaaS Nessus QVD scan data. "
            "Each implemented-requirement covers one NIST SP 800-53 Rev 5 control "
            "referenced in the scanner findings.  "
            "Implementation narratives marked 'REQUIRED' must be completed by the "
            "system owner before ATO submission."
        ),
        "implemented-requirements": implemented_requirements,
    }


# ---------------------------------------------------------------------------
# system-implementation
# ---------------------------------------------------------------------------

def _system_implementation(data: SystemData, config: SystemConfig) -> dict:
    """Build the full system-implementation section."""
    # Index ports and software by IP for fast lookup
    ports_by_ip: dict[str, list[PortEntry]] = defaultdict(list)
    for pe in data.ports:
        if pe.ip_address:
            ports_by_ip[pe.ip_address].append(pe)

    sw_by_ip: dict[str, list[SoftwareEntry]] = defaultdict(list)
    for sw in data.software:
        sw_by_ip[sw.ip_address].append(sw)

    # Components
    components = [_this_system_component(config)]
    components += [_host_component(h, config) for h in data.hosts]
    components += _software_components(data.software)

    # Inventory items
    inventory_items = [
        _inventory_item(h, ports_by_ip, sw_by_ip, config)
        for h in data.hosts
    ]

    return {
        "users": _users(config),
        "components": components,
        "inventory-items": inventory_items,
    }


# ---------------------------------------------------------------------------
# back-matter
# ---------------------------------------------------------------------------

def _back_matter(
    nessus_path: str,
    ppsm_path: Optional[str],
    software_path: Optional[str],
    compliance_path: Optional[str],
) -> dict:
    resources: list[dict] = [
        {
            "uuid": det_uuid(f"resource:nessus-qvd:{nessus_path}"),
            "title": "Nessus Main QVD",
            "description": "CLaaS Nessus vulnerability findings QVD — primary scan data source.",
            "rlinks": [{"href": nessus_path}],
        }
    ]
    if ppsm_path:
        resources.append(
            {
                "uuid": det_uuid(f"resource:ppsm-qvd:{ppsm_path}"),
                "title": "Nessus PPSM QVD",
                "description": "Port/Protocol/Service/MAC network inventory QVD.",
                "rlinks": [{"href": ppsm_path}],
            }
        )
    if software_path:
        resources.append(
            {
                "uuid": det_uuid(f"resource:software-qvd:{software_path}"),
                "title": "Nessus Software QVD",
                "description": "Installed software inventory QVD.",
                "rlinks": [{"href": software_path}],
            }
        )
    if compliance_path:
        resources.append(
            {
                "uuid": det_uuid(f"resource:compliance-qvd:{compliance_path}"),
                "title": "Nessus Compliance QVD",
                "description": "Policy Compliance family results QVD.",
                "rlinks": [{"href": compliance_path}],
            }
        )
    return {"resources": resources}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_ssp(
    data: SystemData,
    config: SystemConfig,
    *,
    nessus_path: str = "",
    ppsm_path: Optional[str] = None,
    software_path: Optional[str] = None,
    compliance_path: Optional[str] = None,
) -> dict:
    """
    Build a complete OSCAL SSP document from QVD-derived data and system config.

    Args:
        data:            :class:`SystemData` loaded from QVD files.
        config:          :class:`SystemConfig` with user-supplied system metadata.
        nessus_path:     Path string for back-matter resource reference.
        ppsm_path:       Optional PPSM QVD path for back-matter.
        software_path:   Optional Software QVD path for back-matter.
        compliance_path: Optional Compliance QVD path for back-matter.

    Returns:
        A dict that serialises directly to a valid OSCAL SSP JSON document.
    """
    return {
        "system-security-plan": {
            "uuid": rand_uuid(),
            "metadata": _metadata(config),
            "import-profile": _import_profile(config),
            "system-characteristics": _system_characteristics(data, config),
            "system-implementation": _system_implementation(data, config),
            "control-implementation": _control_implementation(data, config),
            "back-matter": _back_matter(
                nessus_path, ppsm_path, software_path, compliance_path
            ),
        }
    }


def write_ssp(ssp: dict, output_path: str) -> None:
    """
    Serialise an SSP dict to a JSON file.

    Args:
        ssp:         Dict returned by :func:`build_ssp`.
        output_path: Destination file path (created or overwritten).
    """
    with open(output_path, "w", encoding="utf-8") as fh:
        json.dump(ssp, fh, indent=2, ensure_ascii=False)


def ssp_summary(ssp: dict) -> dict:
    """
    Return a brief summary dict for logging/display purposes.

    Args:
        ssp: Dict returned by :func:`build_ssp`.

    Returns:
        Dict with counts of components, inventory items, and implemented controls.
    """
    root = ssp["system-security-plan"]
    si = root.get("system-implementation", {})
    ci = root.get("control-implementation", {})
    return {
        "document_uuid":    root["uuid"],
        "oscal_version":    root["metadata"]["oscal-version"],
        "system_name":      root["metadata"]["title"],
        "components":       len(si.get("components", [])),
        "inventory_items":  len(si.get("inventory-items", [])),
        "controls":         len(ci.get("implemented-requirements", [])),
    }
